title: Adam G G Smith
logo: /assets/img/logo.png
description: Understanding Earth's dynamic surface with large topographic data sets.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
