title: Adam G G Smith
logo: /assets/img/logo.png
description: Adam G G Smith is a PhD student at UCL and Birkbeck. He works with topography to infer tectonic processes.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
