title: Adam G G Smith
logo: /assets/img/cropped-headshot.png
description: Using topographic inversions to understand Earth's dynamic surface.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
canonical_url: "https://www.adamsmith.github.io"

