title: Adam G G Smith
logo: /assets/img/headshot.JPG
description: Understanding Earth's dynamic surface with large topographic data sets.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
