title: Adam G G Smith
logo: /assets/img/cropped-headshot.png
description: Adam G G Smith is a tectonic geomorphologist, using topographic inversions to understand Earth's dynamic surface.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
